pipeline:
  identifier: Build_jimsheldon_rocketmq_1703010176780
  name: Build rocketmq
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1703010158907
        repoName: jimsheldon/rocketmq
  stages:
    - stage:
        strategy:
          parallelism: 2
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: RunTests
                  name: Run Tests
                  identifier: Run_Tests
                  spec:
                    language: Java
                    buildTool: Maven
                    args: "-B package --file pom.xml"
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    enableTestSplitting: true
