pipeline:
  identifier: Build_jimsheldon_rocketmq_1703010176780
  name: Build rocketmq
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1703010158907
        repoName: jimsheldon/rocketmq
  stages:
    - stage:
        strategy:
          parallelism: 2
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Test
                  identifier: Test1
                  spec:
                    shell: Sh
                    command: |-
                      echo $PATH
                      which mvn
                      which java
                      java --version
              - step:
                  type: Action
                  name: Set up JDK 11
                  identifier: Set_up_JDK_11
                  spec:
                    uses: actions/setup-java@v2
                    with:
                      java-version: "11"
                      distribution: temurin
              - step:
                  type: Run
                  name: Test
                  identifier: Test2
                  spec:
                    shell: Sh
                    command: |-
                      echo $PATH
                      which mvn
                      which java
                      java --version
              - step:
                  type: RunTests
                  name: Run Tests
                  identifier: Run_Tests
                  spec:
                    language: Java
                    buildTool: Maven
                    args: clean install -Dsurefire.rerunFailingTestsCount=5 -DskipITs -DfailIfNoTests=false
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    enableTestSplitting: true
        timeout: 60m
